// Generated by ReScript, PLEASE EDIT WITH CARE


function FormSubmitExtensionEvent(Params) {
  return {};
}

var SubT = {};

var SubmitT = {};

export {
  FormSubmitExtensionEvent ,
  SubT ,
  SubmitT ,
}
/* No side effect */
